package robo.model.event;



public interface EventSource {
  /**
   * Register an event listener for events generated by this source. This will
   * register the listener for all events generated by the source.
   * 
   * @param eventListener
   *          the listener of the events generated by the event source
   * @return true if registration is successful, false otherwise
   */
  public boolean addListener( EventListener eventListener);

  /**
   * Register an event listener for specific event types generated by this
   * source. This will register listener only for specific types of events.
   * 
   * @param eventType
   *          the type of events for which to register
   * @param eventListener
   *          the listener for events of the provided type
   * @return true if registration is successful, false otherwise
   */
  public boolean addListenerForEventType(
      Class< ? extends Event< ?>> eventType, EventListener eventListener);

  /**
   * Notify the listeners about an event created by this source. Normally, this
   * is used to propagate the events to the listeners of this specific event
   * type.
   * 
   * @param event
   *          the event about which the listeners will be notified
   */
  public <T >void trigger( Event< T> event);
}